# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 08:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpage',
            name='hw_responsibles',
            field=models.ManyToManyField(related_name='tools_hw', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolpage',
            name='process_responsibles',
            field=models.ManyToManyField(related_name='tools_process', to=settings.AUTH_USER_MODEL),
        ),
    ]
