# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_eventpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='start_date',
        ),
    ]
