# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160811_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolpage',
            name='hw_responsibles',
        ),
        migrations.RemoveField(
            model_name='toolpage',
            name='process_responsibles',
        ),
    ]
