# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 11:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160812_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='event',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.EventPage'),
        ),
    ]
