# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-19 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_task_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=models.TextField(blank=True, max_length=510, null=True),
        ),
    ]
