# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_eventpage_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
