# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160824_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0, null=True, verbose_name=((0, 'None'), (1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW'))),
        ),
    ]
