# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 10:58
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160812_1255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventPage',
        ),
        migrations.AlterField(
            model_name='task',
            name='event',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Event'),
        ),
    ]
