# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='dummy',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
