# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160829_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toolmodule',
            options={'ordering': ['tool', 'name']},
        ),
        migrations.AddField(
            model_name='task',
            name='requisitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_tasks', to='home.DashboardUser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.DashboardUser'),
        ),
    ]
