# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_auto_20160812_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='description',
            field=models.CharField(blank=True, max_length=510, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
