# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20160829_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.CharField(max_length=256, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Planned')], default=0)),
                ('last_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
