# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_moduletooljoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolpage',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Module'),
        ),
    ]
