# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 08:14
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_toolpage_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testings', to='home.ToolPage'),
        ),
    ]
