# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_requeststatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('requisition_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Requested'), (1, 'Accepted'), (2, 'Rejected'), (3, 'Planned')], default=0)),
                ('rejection_reason', models.CharField(max_length=256, null=True)),
                ('last_update', models.DateField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.DashboardUser')),
                ('tool', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.ToolPage')),
            ],
            options={
                'ordering': ['tool', 'owner'],
            },
        ),
    ]
