# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 20:37
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160830_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['tool', 'owner']},
        ),
        migrations.AddField(
            model_name='request',
            name='tool',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='home.ToolPage'),
        ),
    ]
