# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_module_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduletooljoin',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduletooljoin',
            name='tool',
        ),
        migrations.AddField(
            model_name='module',
            name='andere',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ModuleToolJoin',
        ),
    ]
