# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160830_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
