# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 08:18
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160612_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='andere',
        ),
        migrations.RemoveField(
            model_name='toolpage',
            name='test',
        ),
        migrations.AlterField(
            model_name='module',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='home.ToolPage'),
        ),
    ]
