# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160824_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
