# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 09:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160811_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardadvisoruser',
            name='user',
        ),
        migrations.AlterField(
            model_name='hwtoolresponsibles',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DashboardAdvisorUser',
        ),
    ]
