# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160830_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(choices=[(0, 'Requested'), (1, 'Rejected'), (2, 'Accepted'), (3, 'Planned')], default=0),
        ),
    ]
