# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'HIGH'), (2, 'MEDIUM'), (3, 'LOW')], default=0, null=True),
        ),
    ]
