# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20160811_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='role',
            field=models.IntegerField(choices=[(1, 'HW'), (2, 'Process')], default=1),
        ),
    ]
