# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_dashboarduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processtoolresponsibles',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.DashboardUser'),
        ),
    ]
