# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-02 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160901_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'To Do'), (1, 'In Progress'), (2, 'Done')], default=0),
        ),
    ]
