# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160613_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tool',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.ToolPage'),
        ),
    ]
