# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'To Do'), (1, 'In Progress'), (2, 'Done')], default=0),
        ),
    ]
