# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20160811_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='first_name',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='dashboarduser',
            name='last_name',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
