# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160613_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboarduser',
            name='company',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='dashboarduser',
            name='group',
            field=models.CharField(max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='toolpage',
            name='tool_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
