# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20160905_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='planned_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
