# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_toolpage_vwv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUtilityStatusValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='toolutilitystatusvalue',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='home.UtilityStatus'),
        ),
        migrations.AddField(
            model_name='toolutilitystatusvalue',
            name='tool',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilities', to='home.ToolPage'),
        ),
    ]
