# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_facilitystatuspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Utility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fab')),
            ],
        ),
        migrations.AlterModelOptions(
            name='utilitystatus',
            options={'verbose_name_plural': 'utility status'},
        ),
    ]
