# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160703_0845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utility',
            options={'verbose_name_plural': 'utilities'},
        ),
        migrations.RemoveField(
            model_name='utility',
            name='facility',
        ),
        migrations.AddField(
            model_name='utility',
            name='fab',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='home.Fab'),
        ),
    ]
