# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20160703_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='utility',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.UtilityStatus'),
        ),
    ]
