# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_utility_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utility',
            name='status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.UtilityStatus'),
        ),
    ]
